FROM ubuntu:latest

ENV UBUNTU_SOURCE /etc/apt

COPY ./ /root

WORKDIR /root

# ADD sources.list $UBUNTU_SOURCE/

RUN apt-get update && \
	apt-get install libcurl4-openssl-dev libelf-dev clang llvm -y

COPY ./build/bin/Release/ecli /usr/bin/
RUN chmod +x /usr/bin/ecli

#CMD ./ecli run /root/my/package.json
CMD ["/bin/bash"]