FROM ubuntu:latest

ENV UBUNTU_SOURCE /etc/apt

COPY ./ /root

WORKDIR /root

# ADD sources.list $UBUNTU_SOURCE/

RUN apt-get update && \
	apt-get install libcurl4-openssl-dev libelf-dev clang llvm -y

COPY ./ecli/build/bin/ecli /usr/bin/

#CMD ./ecli run /root/my/package.json
CMD ["/bin/bash"]