FROM ubuntu:latest

ENV UBUNTU_SOURCE /etc/apt

WORKDIR /root

RUN apt-get update -y && \
	apt-get install -y --no-install-recommends libelf1 libelf-dev \
		zlib1g-dev clang llvm libclang-13-dev make cmake git  wget tar && \
	apt-get clean && \
	curl https://sh.rustup.rs -sSf | sh -s	&& \
	rm -rf /var/lib/apt/lists/*

RUN openssl s_client -showcerts -servername github.com -connect github.com:443 </dev/null 2>/dev/null \
	| sed -n -e '/BEGIN\ CERTIFICATE/,/END\ CERTIFICATE/ p'  > github-com.pem	&& \
	cat github-com.pem | tee -a /etc/ssl/certs/ca-certificates.crt

RUN git clone --recurse-submodules https://github.com/eunomia-bpf/eunomia-bpf.git	&& \
	cd eunomia-bpf	&& \
	make bpf-loader	&& \
	make ecli	&& \
	cp build/bin/Release/ecli /usr/bin/	&& \
	chmod +x /usr/bin/ecli

#CMD ecli run /root/my/package.json
CMD ["/bin/bash"]