# build run env
FROM ubuntu:22.04

ENV TZ = Asia/Shanghai

WORKDIR /usr/local/src

RUN apt-get update -y && apt-get install -y --no-install-recommends libelf1 libelf-dev zlib1g-dev clang make llvm wget tar libclang-13-dev && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY ./. /usr/local/src

COPY ./workspace/bin/ecc /usr/bin/
# COPY /opt/wasi-sdk/* /opt/wasi-sdk/

RUN wget --no-check-certificate https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/wasi-sdk-17.0-linux.tar.gz && \
	tar -zxf wasi-sdk-17.0-linux.tar.gz && \
	sudo mkdir -p /opt/wasi-sdk/ && sudo mv wasi-sdk-17.0/* /opt/wasi-sdk/

VOLUME /data/

ENTRYPOINT ["make"]
CMD ["build"]
