on: [push, pull_request]

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu22.04
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: aarch64
          distro: ubuntu22.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            echo "my info: " `uname -a`

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            -v /usr/bin/:/usr/bin/
          install: |
            apt-get update && \
            apt-get install -y --no-install-recommends libelf1 libelf-dev \
                zlib1g-dev clang llvm libclang-13-dev make cmake git  wget tar && \
            apt-get install -y --no-install-recommends ca-certificates	&& \
            update-ca-certificates	&& \
            apt-get clean && \
            curl https://sh.rustup.rs -sSf | sh -s	&& \
            rm -rf /var/lib/apt/lists/*
            mkdir /src && cd /src
            git submodule update --init --recursive --remote
            make bpf-loader && make ecli

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: git-${{ matrix.distro }}_${{ matrix.arch }}

          # The shell to run commands with in the container
          shell: /bin/sh

          # Produce a binary artifact and place it in the mounted volume
          run: |
            cp /src/eunomia-bpf/ecli/build/bin/Release/ecli /usr/bin/	&& \
            chmod +x /usr/bin/ecli