on: [push, pull_request]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7
    steps:
      - uses: actions/checkout@v3
      - name: update remote
        run: |
          git submodule update --init --recursive --remote
          mkdir ~/code
          cp -r ../eunomia-bpf ~/code/
          ls -af ~/code/eunomia-bpf

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          dockerRunArgs: |
            -v ~/code/eunomia-bpf:/usr/eunomia-bpf

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            
            
            apt-get update
            apt-get install -y --no-install-recommends libelf1 libelf-dev \
                zlib1g-dev clang llvm libclang-13-dev make cmake git wget tar curl
            apt-get install -y --no-install-recommends ca-certificates
            update-ca-certificates
            apt-get clean
            
            curl https://sh.rustup.rs -sSf | sh -s -- -y	&& \
            rm -rf /var/lib/apt/lists/*
            cd /usr/eunomia-bpf/ecli
            make build
            
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
          ls ~/code/eunomia-bpf/ecli
